### ISSUE TITLE
XThreads Plugin Updates?

### ISSUE THREAD

**Issue by SerpiusCapricornus** [zingaburga/XThreads-MyBB-Plugin#21]
It has been over 3 years since the XThreads plugin has been updated.

Is it compatible with the latest MyBB 1.18.19 (soon to be .20)?

Are there plans to update/upgrade XThreads to be compatible for the new MyBB 1.9.xx?

I posted the same question on MyBBHacks, but have not gotten a reply.

**Comment by zingaburga** [comment]
> It has been over 3 years since the XThreads plugin has been updated.

Actually, the [last commit](https://github.com/zingaburga/XThreads-MyBB-Plugin/commits/master) is just a few months old.

> Is it compatible with the latest MyBB 1.18.19 (soon to be .20)?

Do you have any reason to believe that it isn't?

> Are there plans to update/upgrade XThreads to be compatible for the new MyBB 1.9.xx?

No clue unfortunately.

**Comment by SerpiusCapricornus** [comment]
> > It has been over 3 years since the XThreads plugin has been updated.
> 
> Actually, the [last commit](https://github.com/zingaburga/XThreads-MyBB-Plugin/commits/master) is just a few months old.
> 

**This is misleading. Just because you made a "commit" does NOT mean the software has been fixed/updated/upgraded.
On top of that, your software is listed on your website was last updated on December 2015.
That is the date that many people go by. Not the date of the GitHub commit. That was September 2018, which is far more than a few months ago.
That last "commit" was technically not a fix/patch for XThreads. It was a response to someone having an issue and your response was that the user adjusting the single line of code themselves. It has nothing to do with the actual fixing of XThreads code.**

> > Is it compatible with the latest MyBB 1.18.19 (soon to be .20)?
> 
> Do you have any reason to believe that it isn't?
> 

**That was not my question. Why are you giving an answer in the form of a question to the original question? This is a classic case of push-back when you do not want to answer the question. A simple Yes or No would have sufficed.**

**Also, there is a lot of coding that still pertains to the MyBB 1.6.xx series, which should have been updated for MyBB 1.8.xx series, but it was never done. Sure, you made some coding changes and/or added coding to make the XThreads work for MyBB 1.8.xx series, but it's sloppy coding and it should be cleaned up to make the plugin more efficient and up-to-par with the latest MyBB and PHP versions.**
 
> > Are there plans to update/upgrade XThreads to be compatible for the new MyBB 1.9.xx?
> 
> No clue, unfortunately.

**What? No clue? You are the person that coded the XThreads plugin, giving an answer like this shows me and others that you really don't care about the XThreads plugins anymore.
If that is the case, you should give coders/programmers the opportunity to work on XThreads and made the necessary updates that need to have XThreads work with the upcoming MyBB 1.9.xx series.**

**Comment by zingaburga** [comment]
> This is misleading. Just because you made a "commit" does NOT mean the software has been fixed/updated/upgraded.

I consider an "update" to be any change of code.  Stuff you see posted, I think is generally referred to as a "release".  Plus, you're posting this on Github, so I think git is quite relevant here.  
Nonetheless, if you were trying to state that it's been 3 years since the last *release*, you would be very correct.

> This is a classic case of push-back when you do not want to answer the question.

Glad you noticed.

> Also, there is a lot of coding that still pertains to the MyBB 1.6.xx series

1.4.x too, as it's the base version of MyBB that XThreads targets.

> it's sloppy coding and it should be cleaned up to make the plugin more efficient and up-to-par with the latest MyBB and PHP versions

Please feel free to point out any examples of sloppy coding, and ideally what to do about it.  I do try to maintain compatibility with MyBB 1.4.x and PHP ~5.1, but if you feel that massive improvements can be made disregarding that compatibility, I'm interested in hearing them regardless.

> You are the person that coded the XThreads plugin, giving an answer like this shows me and others that you really don't care about the XThreads plugins anymore.

I'm not actively adding new features to it, but I have been fixing reported issues and applying compatibility fixes.  I'm unsure if that counts as "not caring" by your definition, but if so, that it is then.

I really don't know what you're expecting.  MyBB 1.9 isn't even out, so how am I supposed to know what I would need to target?  Also, it's not like I can just wave a wand over the code and it gets upgraded - these changes require time and effort (read: **free** time and *voluntary* effort).  Will I get any free time when the next MyBB is released?  Who knows?  Even if I do, will I be willing to spend it on this, or maybe I'll find something which interests me more?

If it's a better answer to your question, I don't feel obliged to do anything with this code.  After all, this is just a hobby project for which I am not receiving any compensation for.

> you should give coders/programmers the opportunity to work on XThreads and made the necessary updates that need to have XThreads work with the upcoming MyBB 1.9.xx series

This plugin is completely open source (GPL licensed), so anyone is free to make changes and redistribute them, including forking and submitting pull requests.  This has been the case since XThreads was initially released back in 2010.

If you feel that you can seriously improve XThreads, make the coding less sloppy, improve compatibility, or just think my attitude sucks, I strongly recommend you forking the project and making your own changes as you will.  Feel free to submit pull requests and/or release your XThreads fork as you wish.

**Comment by SerpiusCapricornus** [comment]
Wow! Took you over 1 year to close this. Goes to show you how unreliable you really are.

**Comment by zingaburga** [comment]
And here I was waiting in anticipation for your response.  Every night, I wondered what new insights SerpiusCapricornus would bring to my life.  It was with great sadness that I hit the Close button, knowing that, even after a year, my long awaited response would likely not arrive.

Thank you for showing up again, with your highly informative and useful comment.  I can finally rest peacefully knowing that my life has been transformed by your wisdom.  
My hope is that you'd bring even more insights in your future comments.  Please do post again, and display your incredible intellect upon the world.
